### ISSUE TITLE
Links in the readme are broken

### ISSUE THREAD

**Issue by maxbiostat** [Novartis/RBesT#5]
Links in the "Getting started" section are broken currently.

**Comment by weberse2** [comment]
Thanks for reporting!

I have still been wresting with this pkgdown setup. I will use absolute hyper refs so they work on the GitHub landing page and on the homepage of RBesT: https://opensource.nibr.com/RBesT/

Once this is merged, I will close this very first issue here.

**Comment by maxbiostat** [comment]
Many thanks!

**Comment by weberse2** [comment]
Things took a bit longer than I thought...but the just accepted 1.6-6 RBesT release now has fixed URLs in the `README.md`. Thanks for reporting!
